language: php, go

go:
  - "1.8"
  - "1.9"

php:
  - '5.4'
  - '5.6'
  - '7.1'

install:
  - composer require wsdl2phpgenerator/wsdl2phpgenerator
  - composer dumpautoload

script:
  - php php/src/build.php
  - cd go && make client
